@startuml
'https://plantuml.com/class-diagram

class Plateau{

    + int upperX;
    + int upperY;
    + int lowerX;
    + int lowerY;


    + Plateau(int upperX, int upperY);


}

class Rover{
    + int roverId;
    + Orientation Direction;
    + Plateau plateau;
    + int[] roverCount
    + Rover(int x, int y, Orientation orientation);
    + boolean execute(char command);
    + int[] commands();
    + MarRoverPos();
    + void moveRover()
}
Plateau "1" -> "many" Rover
enum Orientation{
    N, E, S, W
    + Orientation left();
    + Orientation right();
}

@enduml